### ISSUE TITLE
ResourceInfo/SchemaInfo supports "const" callexpr flattend

### ISSUE THREAD

**Issue by magodo** [bflad/tfproviderlint#115]
Currently the analyzers to collect facts for resource info and schema info only works for those been fully defined. But this is not the case for at least azurerm provider, since there are some helper function which simply return a predefined schema strucuture, or some helper function.

I think for those func decl whose body contains only one return statement (const callexpr), it is possible to flatten it into where it is invoked. We can do it by using the `astutil.Apply()` together with `Curosr.Replace()` to modify the ast a bit. However, the cons is the replaced ast node will no longer works with the file set in the `pass`.

With this supported, we can also add another rule to disallow user to define non-const callexpr to be used for resource info or schema info definition.

**Comment by bflad** [comment]
Hi @magodo 👋 Thank you for submitting this. I'd like to understand a little more about this use case before discussing it more. We would prefer to not introduce complexity beyond the standard `go/analysis` framework where possible.

Can you please show example code you are trying to analyze/report? Thank you.

**Comment by magodo** [comment]
Hi @bflad 
The actual use case is that we have some schema ordering rule in azurerm provider, the rule is like below:

> The order of property declaration in schema should follow rules below, the former rules apply first:
> 1. `name` -> `resource_group_name` -> `location` (if any) -> other URL component properties (if any)
> 2. `tags` (if any) is always the last property
> 3. `ForceNew` + `Required` -> `ForceNew` + `Optional` -> `Required` -> `Optional` -> `Computed`
> 4. Order by property name alphabet order

The rule can (hopefully) be checked with some improvement of current `resourceinfo`/`schema` analyzer once we can bake the schema information into `ResourceInfo.Resource` and keep the order info for them. While as you know it can only work when the resource definition is fully defined in one single function.

In some not so frequent cases, some resource has their resource definition made up by some other functions. E.g. in azure there are a bunch of helper function to return some schema definition for some common attributes, like [resource_group](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/resource_group.go#L12).

To deal with that, I have some demo code [here](https://gist.github.com/magodo/c1fb09b6f032abc1d519933f37ca9180) that you can have a look. There are some improvements that we can make to not break the fileset/pos information, e.g.:

1. We can provide some hook to provider linter so that they can register the definition of those predefined schema helper, and once we hit those node, we just replace them with the predefined schema.
2. For user defined schema/resource helper function, we can only assume they are in the same package of the file under analyzing, so that we can always get the node without doing force loading (which breaks api contract of `go/analysis`). Though this is a limitation, it actually a best effort.

**Comment by bflad** [comment]
Hi again 👋 Thank you for the detailed explanation.

I guess its best to say upfront that this tool will likely not cover every usage of "expanding" complex schema definitions (such as the results of function calls) into single passes. The current schema handling covers the implementation of the majority of Terraform Provider codebases today, without being too complex in the analysis implementation itself. While it may be feasible via AST handling, that type of replacement feels outside the regular usage patterns of this type of analysis. There's a tradeoff when doing static analysis in general that it is going to be very hard to capture all use cases since there are many permutations that source code can be written. 

That said, the linking of expanded `Resource` and `Schema` certainly seems useful, simple enough in implementation, and we can work through getting those parts of #129 merged.

It is also worth mentioning that the ordering checks mentioned above can at least be mostly implemented today, even without worrying about function call replacement. The `passes/helper/schema/schemamapcompositelit` analyzer will have an ordered list of `*ast.KeyValueExpr`, which you can use to perform custom logic against each of the keys and values.  It wouldn't be perfect, but if an `*ast.CallExpr` is encountered in the value instead of a `*ast.UnaryExpr` and `*ast.CompositeLit`, it can be skipped.

I also forget if changing those function calls to be constants/variables instead would make the AST substitution easier. If so, that seems a little more likely for implementation as well.

**Comment by magodo** [comment]
Hi @bflad Thank you for the detailed thought here :+1: 

I totally agree with you to keep linter simple and maintainable. I didn't considered to make those function calls to be constants/variables previously and I think that would be a promising direction to go!

**Comment by bflad** [comment]
Basic linking between `ResourceInfo` and `SchemaInfo` has been merged and will release with version 0.15.0 of tfproviderlint. If there are specific other feature requests, let's create individual issues for tracking or decision making. 😄
