### ISSUE TITLE
schema.NewSchemaInfo() sets Elem field to an unexported type

### ISSUE THREAD

**Issue by armsnyder** [bflad/tfproviderlint#206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint and terraform-plugin-sdk Version

```console
$ tfproviderlint -version

$ go mod graph | cut -d' ' -f 1 | grep terraform-plugin-sdk | uniq

```

`github.com/bflad/tfproviderlint v0.18.0`

```
github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.0
github.com/hashicorp/terraform-plugin-sdk@v1.9.0
github.com/hashicorp/terraform-plugin-sdk@v1.15.0
```

### Affected Check(s) or Function(s)

* `schema.NewSchemaInfo()`

### Expected Behavior

I use this package as a library for writing custom TF checks. I want to be able to access attributes on nested blocks, for schemas that are parsed using `schema.NewSchemaInfo()`.

```go
s := schema.NewSchemaInfo(cl, pass.TypesInfo)
nestedResource, ok := s.Schema.Elem.(*schema.resourceType)  # Compiler error
```

### Actual Behavior

The package sets the nested resource to the `Elem` field; but it is a unexported type, so I am unable to do a type assertion and read the nested resource. (`Elem` type is `interface{}`, so a type assertion is required.)

Using the `resourceinfo` or `schemainfo` passes is not a good workaround for me, because I need to know the parent of the nested resource.

### References

* https://github.com/bflad/tfproviderlint/blob/599453fb7420898a3442b0d78bdae25acc75b340/helper/terraformtype/helper/schema/type_schema.go#L215

**Comment by bflad** [comment]
Hi @armsnyder 👋  Thank you for raising this. These Go types were meant to be internal (unexported) in this codebase to prevent the compatibility maintenance burden when their design is not well understood yet. It is not a permanent choice, but I would want to understand how this data is being used before committing to supporting it in that manner and I would love to help you in some fashion here. Would you be able to elaborate more on what you are trying to achieve using this information?

Another interesting thing to note here is while in certain specific situations that this tooling may be able to "recreate" a resource schema, it is very difficult to guarantee these abilities given that we are working at a low level of the programming language. We have shied away from introducing checks which are heavily dependent on multiple pieces of coupled code (e.g. levels of schema) for the reason above due to highly variable coding styles. In some cases it would be preferable to instead rely on the `terraform providers schema -json` output since its the fully constructed and finalized schema information. That is not to say these types of enhancements are out of the question, but rather it can be helpful to draw design decisions. 👍

**Comment by armsnyder** [comment]
Hi @bflad! Thanks for the reply. I can appreciate that this codebase (or parts of it) were never intended to be a library; however the [AWS provider has an awsproviderlint tool](https://github.com/terraform-providers/terraform-provider-aws/tree/master/awsproviderlint) which does this, so I didn't realize that it was discouraged.

My exact use case is: I want to write a rule that checks for resource attributes that are not documented in the provider docs page for the resource.

To do that, I need a way of listing the attribute names for a resource. Since resources can have nested schemas, it's tricky to do using the helper analyzers, where the relationships between different schemas are not preserved. So, I was hoping I could write a new analyzer that traverses each resource and collects schema info across all schemas contained in the resource.

I take your point about the complexity when you have to consider different design patterns. The codebase I work in ([terraform-provider-gitlab](https://github.com/gitlabhq/terraform-provider-gitlab)) has a pretty consistent code style, so to me this kind of check would be worth it, even if it misses a few edge cases.

**Comment by bflad** [comment]
@armsnyder for that use case I would strongly encourage using the `terraform providers schema -json` output -- its guaranteed to be correct with the finalized schema, no matter the underlying coding styles. This is how we currently provide information to https://github.com/bflad/tfproviderdocs for various documentation checks and which has a [similar feature request](https://github.com/bflad/tfproviderdocs/issues/16) 😉 . To see how to build and provide the schema JSON information to tooling, you may find this [GitHub Actions workflow in the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/7e50aaad2a6eb83a33f450f85ac7e4d18535c7dd/.github/workflows/terraform_provider.yml#L266) helpful.

For what its worth, there is also some work being done to write a more official tool: https://github.com/hashicorp/terraform-plugin-docs -- tfproviderdocs was written as a proof of concept for some of the validation pieces.

> I can appreciate that this codebase (or parts of it) were never intended to be a library; however the AWS provider has an awsproviderlint tool which does this, so I didn't realize that it was discouraged.

I can add some verbiage to the README in this project, but the general idea is that these analyzers here can provide some primitives for downstream provider-specific tooling, but we do have to consider some places where trying to accurately handle tightly coupled code (which can take many forms in AST) would introduce the complexity/maintenance noted above.

**Comment by armsnyder** [comment]
@bflad Thanks for taking the time to point me in the right direction. I'll try one or a combination of those tools. 😄

**Comment by bflad** [comment]
Hey @armsnyder 👋  I hope the above helped out. I'm going to close this out without any changes due to the potential complexity and available workarounds, but I really appreciate you submitting this issue.

The team that manages the Terraform Plugin SDK is currently designing the next major iteration in github.com/hashicorp/terraform-plugin-framework. One of the overall goals is to support more compile-time checks within provider implementations as well as consider additional tooling that is potentially not reliant on the Terraform plugin protocol and Terraform CLI. Changes there are relatively expensive in terms of operational resources and ensuring compatibility. Whether this is natively allowing provider binaries to offer separate gRPC endpoints or code inspection based is yet to be determined, but hopefully this space can see some additional enhancements in the future.
