### ISSUE TITLE
New Extra Check: flag fmt.Errorf messages that begin with error or print pointers

### ISSUE THREAD

**Issue by stephybun** [bflad/tfproviderlint#245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After refactoring several services and reviewing PRs for the azure provider I noticed that the error messages across the provider are fairly inconsistent. For a start it would be great if there could be checks that prevent error messages from starting with the word `error` and to flag error messages that interpolate a pointer instead of it's value.

### New Checks(s)

* XR009, XR010

### Flagged Provider Code

```go
fmt.Errorf("error reading some service")
fmt.Errorf("Error reading some service")
fmt.Errorf("ERROR reading some service")

fmt.Errorf("retrieving: %s", id)    // where id is a pointer
```

### Passing Provider Code

```go
// no usage
```

**Comment by bflad** [comment]
Hi @stephybun 👋 Thank you for raising this! This is a great idea for static analysis to enforce certain error messaging standards. It seems, however, that this project might not the best place to host this particular style checking since it would be generic for any Go code, not just Terraform Providers developed with the Terraform Plugin SDK. Each Terraform Provider may also have its own standards in this regard.

I would envision, if this doesn't exist already, creating a separate Go module that finds `fmt.Errorf()` call expressions and runs rules against the first parameter. For example, this might be something that could be implemented with a `go/analysis` analyzer, similar to how https://github.com/bflad/gopaniccheck looks for call expressions like `log.Panicf()`. If implemented this way, it can potentially be run as a standalone command or introduced into projects like [`golangci-lint`](https://golangci-lint.run/). There are other potential options for this type of static analysis that might be easier to implement as well, such as creating [`semgrep`](https://semgrep.dev/) rules.

Thanks again for proposing this.
