### ISSUE TITLE
Document if there is a way to use tfproviderlint within a test

### ISSUE THREAD

**Issue by remyleone** [bflad/tfproviderlint#250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ideally, I would like to have a fixed version of tfproviderlint that is pinned in the go.mod. By doing so I would be able to upgrade it regularly using classical dependabot notifications. If the dependency is used only in a test file, it will not make my provider bigger as well. Is there a way to use tfproviderlint as a dependency in a test?

**Comment by bflad** [comment]
Hi @remyleone 👋 Thank you for raising this.

This is a Go module ecosystem issue where it doesn't natively support "development" dependencies like other ecosystems, such as NPM, in a single `go.mod` file. Go also treats dependencies in testing files the same as production files (at least for one level of its MVS algorithm post Go 1.17). Beyond pointing at "conventions" in the Go community, this is more of a Go language problem to solve or document better rather than anything specific to this Go module. There's https://github.com/golang/go/issues/25922 which is a lengthy older thread on this subject and https://github.com/golang/go/issues/48429 with a forward looking proposal. My personal position here is that those would serve as better references, since any recommendation here could become out of date by the language maintainers or the ecosystem at large.

That being said, if you're looking for one solution that does work today, it would be to introduce a separate `go.mod` file and associated "tools.go" file with tooling dependencies. This helps ensure the tooling dependencies do not adversely affect the rest of the Go module. The [cloudflare provider](https://github.com/cloudflare/terraform-provider-cloudflare/tree/master/tools) has a nice example of this setup. In this case, you can add an additional Dependabot `gomod` ecosystem configuration to point at the tooling `go.mod` to ensure it suggests updates.
