### ISSUE TITLE
Add support for terraform-plugin-framework

### ISSUE THREAD

**Issue by ndrpnt** [bflad/tfproviderlint#253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support providers written with [`terraform-plugin-framework`](https://github.com/hashicorp/terraform-plugin-framework):
* Port existing rules that are relevant for `terraform-plugin-framework`
* Consider both `terraform-plugin-framework` and `terraform-plugin-sdk/v2` when adding rules
* Add rules specific to `terraform-plugin-framework`

### References

* `terraform-plugin-framework` is ["the future of Terraform plugin development"](https://www.terraform.io/plugin/which-sdk#:~:text=It%20represents%20our%20vision%20of%20the%20future%20of%20Terraform%20plugin%20development.). It is currently in technical preview and breaking changes happen
* `terraform-plugin-framework` and `terraform-plugin-sdk/v2` can be mixed in a single provider with [`terraform-plugin-mux`](https://github.com/hashicorp/terraform-plugin-mux)
* `terraform-plugin-framework` does not have a testing package yet. For now, `terraform-plugin-sdk/v2` is used to write tests

**Comment by bflad** [comment]
Are there specific checks that you are looking for? If you have suggestions, I'd encourage creating issues in the terraform-plugin-framework repository to discuss coding issues or potential stylistic improvements.

Ideally, it is still in an incubating state where we may be able to implement or "correct" types, functions, etc. to prevent the similar issues present in terraform-plugin-sdk. These issues could potentially be handled at compile time by changing those definitions or offering more robust built-in unit testing functions, rather than being reliant on external tooling such as this. That's not to say there isn't a place for static analysis like this project offers, but now is a great time to try and prevent things where possible before we need to introduce stricter compatibility promises.

**Comment by ndrpnt** [comment]
Hi @bflad thanks for the reply. You are completely right, issues are better addressed directly in the framework, where possible. I don't have any specific check in mind, but looking at the existing ones, I feel that some might stay relevant for `terraform-plugin-framework`. E.g. [R013](https://github.com/bflad/tfproviderlint/tree/main/passes/R013), [R014](https://github.com/bflad/tfproviderlint/tree/main/passes/R014), [R017](https://github.com/bflad/tfproviderlint/tree/main/passes/R017), [R018](https://github.com/bflad/tfproviderlint/tree/main/passes/R018).

I didn't see any related issue so I wanted to make sure you had `terraform-plugin-framework` in the radar. I didn't check you were working at HashiCorp ! I'm closing the issue since there are no real actionnable needs associated to it.
