### ISSUE TITLE
internal error: package "context" without types was imported

### ISSUE THREAD

**Issue by remyleone** [bflad/tfproviderlint#255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint and terraform-plugin-sdk Version

```console
$ tfproviderlint -version
tfproviderlint v0.28.1

$  go mod graph | cut -d' ' -f 1 | grep terraform-plugin-sdk | uniq
github.com/hashicorp/terraform-plugin-sdk/v2@v2.11.0

$ go version
go version go1.18 darwin/amd64
```

### Affected Check(s) or Function(s)

* AT###

### Expected Behavior

The program runs.

### Actual Behavior

```
$ tfproviderlint run ./...
tfproviderlint: internal error: package "context" without types was imported from "github.com/scaleway/terraform-provider-scaleway/v2/scaleway"
```

You can use the master branch and it reproduces: <https://github.com/scaleway/terraform-provider-scaleway>

**Comment by remyleone** [comment]
Would you consider adding dependabot to this repository? If you are interested, I can provide you with a merge request :)

**Comment by davewongillies** [comment]
I get this same error too, but with a different package (its an internal project, so the URL is redacted, sorry):

```
$ tfproviderlint ./...
tfproviderlint: internal error: package "crypto/tls" without types was imported from "<redacted>"
```

**Comment by bflad** [comment]
> Would you consider adding dependabot to this repository?

Normally, I'd be all for this (and actually, I was caught off guard myself that it was not already in place), although I'm leery of introducing it though since I specifically want this project to not _force_ terraform-plugin-sdk dependency upgrades on folks. I'd rather have this module's dependencies only tracking the minimum versions where possible there. I guess the best compromise in this scenario might be to create a dependabot configuration which explicitly ignores those two dependencies with comments explaining why they are ignored. I guess we'll also see how "noisy" x/tools updates become.

**Comment by jimeh** [comment]
Any updates on when/how this might be resolved? :)
